### ISSUE TITLE
[Feature Request] Automagically update library

### ISSUE THREAD

**Issue by roblav96** [patrick-klein/script.library.integration.tool#3]
I have this tool synced up with my Trakt watchlist folder and whenever I add/remove a movie I need to manually click `Update Library` which is tedious as you could imagine. Honestly I don't even understand the reason behind the `Staging` feature. 😁 I imagine adding a folder via `Sync directory to library` and then that's it. Maybe add a polling update interval setting. So far this is one of my favorite addons! Great work =]

**Comment by patrick-klein** [comment]
So there are a few steps that need to happen for this to happen *automagically*.

1)  Eligible items should skip the staging area when being added for the first time or a synced directory is updated.  This is something I was wanted to add for a while but it required a large refactor of the code.  I was able to add this in the version 0.4.0 update, where it's available as a setting for both movies and episodes.  TV show episodes still need to go to staging if they don't have an episode number in the name.  ✅

2)  After an item is added or synced directories are updated, the Kodi library needs to be updated and/or cleaned.  It's simple enough to call these commands for the entire library from the addon, but I don't want to have them run automatically unless I can limit their scope to only the managed directories (and hopefully use a more subtle interface).  Still investigating ways to do this.  TODO

3)  Since remote content changes occasionally, there needs to be a mechanism to trigger this whole process intermittently.  This can be done with a background service.  It's shouldn't be hard to implement, but it may be a resource hog while it runs.  Ideally it would be be possible to assign different rates to different synced directories (either daily/weekly/bi-weekly/monthly).  There should also be a timeout so at most *x* number of minutes are spent updating each day, and anything that didn't get updated would roll-over to the next day.  Would need to develop some sort of priority queue to keep track of what gets updated when.  This would be absolutely necessary for people with many synced directories, or else it might spends hours everyday trying to update everything.  TODO

**Comment by patrick-klein** [comment]
Also thanks for the praise!  Much appreciated :)
